admin:
  access_log_path: /dev/null
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
    - name: landing_page_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 80 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_http
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: landing_page
                      domains: ["$ATALA_PRISM_DOMAIN", "$ATALA_PRISM_LANDING_DOMAIN"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: landing_page_service }
                    - name: prism_console
                      domains: ["$ATALA_PRISM_CONSOLE_DOMAIN"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: prism_console_service }
                    - name: prims_sdk_website_docs
                      domains: ["$ATALA_PRISM_SDK_WEBSITE_DOCS_DOMAIN"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: prism_sdk_website_docs_service }
                http_filters:
                  - name: envoy.router

    - name: grpc_proxy_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 8080 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_grpcproxy
                route_config:
                  name: local_route
                  virtual_hosts:
                    - name: local_service
                      domains: ["*"]
                      routes:
                        # connector
                        - match: { prefix: "/io.iohk.atala.prism.protos.ConnectorService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.ContactConnectionService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialViewsService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.intdemo.protos." }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        # node
                        - match: { prefix: "/io.iohk.atala.prism.protos.NodeService" }
                          route: { cluster: node_service, max_grpc_timeout: 0s }
                        # mirror
                        - match: { prefix: "/io.iohk.atala.mirror.protos." }
                          route: { cluster: mirror_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.kycbridge.protos." }
                          route: { cluster: kycbridge_service, max_grpc_timeout: 0s }
                        # console
                        - match: { prefix: "/io.iohk.atala.prism.protos.ConsoleService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.ContactsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialIssuanceService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialTypesService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.GroupsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialsStoreService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialTypeCategoriesService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                      cors:
                        allow_origin_string_match: { suffix: "$ATALA_PRISM_DOMAIN" }
                        allow_methods: GET, PUT, DELETE, POST, OPTIONS
                        allow_headers: keep-alive,user-agent,cache-control,content-type,content-transfer-encoding,custom-header-1,x-accept-content-transfer-encoding,x-accept-response-streaming,x-user-agent,x-grpc-web,grpc-timeout,request-nonce,did,did-key-id,did-signature,public-key,signature,trace-id,prism-auth-token
                        max_age: "1728000"
                        expose_headers: grpc-status,grpc-message,userid,userId
                http_filters:
                  - name: envoy.grpc_web
                  - name: envoy.filters.http.grpc_stats
                  - name: envoy.cors
                  - name: envoy.router
    - name: grpc_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 8081 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_grpc

                route_config:
                  virtual_hosts:
                    - name: grpc
                      domains: ["*"]
                      routes:
                        # connector
                        - match: { prefix: "/io.iohk.atala.prism.protos.ConnectorService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.ContactConnectionService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialViewsService" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.intdemo.protos." }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                        # node
                        - match: { prefix: "/io.iohk.atala.prism.protos.NodeService" }
                          route: { cluster: node_service, max_grpc_timeout: 0s }
                        # mirror
                        - match: { prefix: "/io.iohk.atala.mirror.protos." }
                          route: { cluster: mirror_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.kycbridge.protos." }
                          route: { cluster: kycbridge_service, max_grpc_timeout: 0s }
                        # console
                        - match: { prefix: "/io.iohk.atala.prism.protos.ConsoleService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.ContactsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialIssuanceService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialTypesService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.GroupsService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialsStoreService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                        - match: { prefix: "/io.iohk.atala.prism.protos.CredentialTypeCategoriesService" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                http_filters:
                  - name: envoy.filters.http.grpc_stats
                  - name: envoy.router
    - name: connector_grpc_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 50051 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_grpc
                route_config:
                  virtual_hosts:
                    - name: connector
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: connector_service, max_grpc_timeout: 0s }
                http_filters:
                  - name: envoy.filters.http.grpc_stats
                  - name: envoy.router
    - name: node_grpc_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 50053 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_grpc
                route_config:
                  virtual_hosts:
                    - name: node
                      domains: ["*"]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: node_service, max_grpc_timeout: 0s }
                http_filters:
                  - name: envoy.filters.http.grpc_stats
                  - name: envoy.router
    - name: management_console_grpc_listener
      address:
        socket_address: { address: 0.0.0.0, port_value: 50054 }
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.config.filter.network.http_connection_manager.v2.HttpConnectionManager
                codec_type: auto
                stat_prefix: ingress_grpc
                route_config:
                  virtual_hosts:
                    - name: management_console
                      domains: [ "*" ]
                      routes:
                        - match: { prefix: "/" }
                          route: { cluster: management_console_service, max_grpc_timeout: 0s }
                http_filters:
                  - name: envoy.filters.http.grpc_stats
                  - name: envoy.router
  clusters:
    - name: connector_service
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: connector_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$CONNECTOR_ADDRESS"
                      port_value: "$CONNECTOR_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% (default is 85%) ...
        failure_percentage_threshold: 50
        # ... when there are at least two instances active ...
        failure_percentage_minimum_hosts: 2
        # ... for 2 minutes
        base_ejection_time: "120s"
    - name: node_service
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: node_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$NODE_ADDRESS"
                      port_value: "$NODE_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% (default is 85%) ...
        failure_percentage_threshold: 50
        # ... when there are at least two instances active ...
        failure_percentage_minimum_hosts: 2
        # ... for 2 minutes
        base_ejection_time: "120s"
    - name: management_console_service
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: { }
      lb_policy: round_robin
      load_assignment:
        cluster_name: management_console_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$MANAGEMENT_CONSOLE_ADDRESS"
                      port_value: "$MANAGEMENT_CONSOLE_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% (default is 85%) ...
        failure_percentage_threshold: 50
        # ... when there are at least two instances active ...
        failure_percentage_minimum_hosts: 2
        # ... for 2 minutes
        base_ejection_time: "120s"
    - name: mirror_service
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: mirror_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$MIRROR_ADDRESS"
                      port_value: "$MIRROR_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% (default is 85%) ...
        failure_percentage_threshold: 50
        # ... when there are at least two instances active ...
        failure_percentage_minimum_hosts: 2
        # ... for 2 minutes
        base_ejection_time: "120s"
    - name: kycbridge_service
      connect_timeout: 5s
      type: strict_dns
      http2_protocol_options: {}
      lb_policy: round_robin
      load_assignment:
        cluster_name: kycbridge_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$KYC_BRIDGE_ADDRESS"
                      port_value: "$KYC_BRIDGE_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% (default is 85%) ...
        failure_percentage_threshold: 50
        # ... when there are at least two instances active ...
        failure_percentage_minimum_hosts: 2
        # ... for 2 minutes
        base_ejection_time: "120s"
    - name: landing_page_service
      connect_timeout: 5s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: landing_page_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$LANDING_PAGE_ADDRESS"
                      port_value: "$LANDING_PAGE_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% for 2 minutes, assuming there are at least 2 instances
        failure_percentage_threshold: 50
        failure_percentage_minimum_hosts: 2
        base_ejection_time: "120s"
    - name: prism_console_service
      connect_timeout: 5s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: prism_console_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$PRISM_CONSOLE_ADDRESS"
                      port_value: "$PRISM_CONSOLE_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% for 2 minutes, assuming there are at least 2 instances
        failure_percentage_threshold: 50
        failure_percentage_minimum_hosts: 2
        base_ejection_time: "120s"
    - name: prism_sdk_website_docs_service
      connect_timeout: 5s
      type: strict_dns
      lb_policy: round_robin
      load_assignment:
        cluster_name: prism_sdk_website_docs_service
        endpoints:
          - lb_endpoints:
              - endpoint:
                  address:
                    socket_address:
                      address: "$PRISM_SDK_WEBSITE_DOCS_ADDRESS"
                      port_value: "$PRISM_SDK_WEBSITE_DOCS_PORT"
      outlier_detection:
        # eject instance that has failure rate > 50% for 2 minutes, assuming there are at least 2 instances
        failure_percentage_threshold: 50
        failure_percentage_minimum_hosts: 2
        base_ejection_time: "120s"
